experiment:
  config_id: GAN_D1b_gru768
  output_dir: runs/ablation/GAN_D1b_gru768
model:
  prelu_type:
  dw_residual: false
  use_eca_f: false
  main_block_eca_f: false
  skip_gate:
  dw_subpixel: false
  gru_hidden: 768
training:
  use_gan: true
  num_d_scales: 3
loss:
  lamda_adv: 0.05
  lambda_fm: 2.0
